export const CHANNEL_CREATE_REQUEST = "CHANNEL_CREATE_REQUEST";
export const CHANNEL_CREATE_SUCCESS = "CHANNEL_CREATE_SUCCESS";
export const CHANNEL_CREATE_FAIL = "CHANNEL_CREATE_FAIL";
export const CHANNEL_CREATE_RESET = "CHANNEL_CREATE_RESET";

export const CHANNEL_FETCH_REQUEST = "CHANNEL_FETCH_REQUEST";
export const CHANNEL_FETCH_SUCCESS = "CHANNEL_FETCH_SUCCESS";
export const CHANNEL_FETCH_FAIL = "CHANNEL_FETCH_FAIL";
export const CHANNEL_FETCH_RESET = "CHANNEL_FETCH_RESET";

export const SET_CURRENT_CHANNEL = "SET_CURRENT_CHANNEL";
